name: app

type: php:8.4

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - iconv
        - pdo_pgsql
        - pgsql

variables:
    env:
        APP_ENV: 'prod'
    php:
        opcache.preload: config/preload.php

build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var/cache": { source: local, source_path: var/cache }
    "/var": { source: local, source_path: var }

relationships:
    database: "postgresql:postgresql"
    
hooks:
    build: |
        set -e
        export APP_ENV=prod
        export APP_DEBUG=0
        composer install --no-dev --optimize-autoloader
        php bin/console cache:clear --no-debug

    deploy: |
        set -e
        export APP_ENV=prod
        export APP_DEBUG=0
        php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

workers:
    messenger:
        size: XS
        resources:
            base_memory: 64
            memory_ratio: 128
        commands:
            start: symfony console --time-limit=3600 --memory-limit=64M messenger:consume async

crons:
    security-check:
        spec: '50 23 * * *'
        cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape COMPOSER_ROOT_VERSION=1.0.0 COMPOSER_AUDIT_ABANDONED=ignore composer audit --no-cache; fi
    clean-expired-sessions:
        spec: '17,47 * * * *'
        cmd: croncape php-session-clean