app = "webscraperapi"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "prod"
  PHP_FPM_DOCUMENT_ROOT = "/app/public"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[processes]
  web = "heroku-php-apache2 public/"
  messenger = "php /app/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
