app = "webscraper-api"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "prod"

[[services]]
  processes = ["web"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[processes]
  web = "apache2-foreground"
  messenger = "php /app/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  processes = ["messenger"]
  internal_port = 8081
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    port = 5000
    protocol = "tcp"
