# fly.toml app configuration file generated for webscraper-api on 2025-05-22T00:34:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weathered-glitter-9529'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "/usr/local/bin/entrypoint.sh sh -c 'nginx && php-fpm'"
  worker = "php bin/console messenger:consume async  --memory-limit=256M --limit=1000"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  processes = ['worker']
